# Generated by Django 6.0 on 2025-12-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название сайта')),
                ('description', models.TextField(verbose_name='Описание сайта')),
                ('logo', models.ImageField(upload_to='', verbose_name='лого')),
                ('phone_number', models.CharField(max_length=30, verbose_name='Номкр телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='емаил')),
                ('address', models.CharField(max_length=30, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Информация о сайте',
                'verbose_name_plural': 'Информация о сайте',
            },
        ),
    ]
